### ISSUE TITLE
Not printing specified value by ticker

### ISSUE THREAD

**Issue by virangvasani** [coinables/bittrex#3]
I am working on crypto- Bot. So I got some reference from your post and bittrex API Documentation but I am getting one problem with printing a specified term called Ask Price.

As you can see in below part of a code It's print a Bid, Ask & the Last price of TRX. But as you wrote in your code to print only Available balance the same thing I am trying to do the same but it's returning a BID, ASK & the LAST price, it's not printing only Ask price. 

I am attaching program along with its output.

code :
```
function getticker(){
    $uri='https://bittrex.com/api/v1.1/public/getticker?market=BTC-TRX';
    $ch = curl_init($uri);
    $execResult = curl_exec($ch);
    $obj = json_decode($execResult, true);
    $val = $obj["result"]["Ask"];
    echo 'Ticker end'.$val;
    print_r($val);
    }
```

Output:

`{"success":true,"message":"","result":{"Bid":0.00000848,"Ask":0.00000850,"Last":0.00000850}}`

**Comment by coinables** [comment]
It's in JSON so you pick the data that you want, and then if it has a parent you must state the parent first. In this example "Ask" is nested within "result" so you would call `["result"]["Ask"]`

```
function getticker(){
    $uri='https://bittrex.com/api/v1.1/public/getticker?market=BTC-TRX';
    $ch = curl_init($uri);
    $execResult = curl_exec($ch);
    $obj = json_decode($execResult, true);
    $val = $obj["result"]["Ask"];
    echo 'Ticker end'.$val;
    print_r($val);
    }

$var = getticker();
$mychoice = $var["result"]["Ask"];
echo $mychoice;

```
